# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Does God Dice?
subtitle: ''
description: Fallenwood's blog.
# keywords: []
author: fallenwood
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://fallenwood.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
  pretty_urls:
    trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
    trailing_html: true # Set to false to remove trailing '.html' from permalinks
  

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: 
  enable: false # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:
# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
## theme: landscape-plus
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html

deploy:
  type: git
  repo:
    github: git@github.com:fallenwood/fallenwood.github.io.git,master

# theme-next
############################################################################################################################################
theme_config:
  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/share-your-work/licensing-types-examples
  # Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
  # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: false
    language:


  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  #scheme: Muse
  scheme: Mist
  #scheme: Pisces
  #scheme: Gemini

  # Dark Mode
  darkmode: false


  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimiter is the target link, value after `||` delimiter is the name of Font Awesome icon.
  # When running the site in a subdirectory (e.g. yoursite.com/blog), remove the leading slash from link value (/archives -> archives).
  # External url should start with http:// or https://
  menu:
    home: / || fa fa-home
    tags: /tags/ || fa fa-tags
    #categories: /categories/ || fa fa-th
    #archives: /archives/ || fa fa-archive
    #schedule: /schedule/ || fa fa-calendar
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat
    about: /about/ || fa fa-user

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: false


  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  sidebar:
    # Sidebar Position.
    #position: left
    position: right

    # Manual define the sidebar width. If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    #width: 300

    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: post

    # Sidebar padding in pixels.
    padding: 18
    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
    offset: 12
    # Enable sidebar on narrow view (only for Muse | Mist).
    onmobile: false

  # Sidebar Avatar
  avatar:
    # Replace the default image and set the url here.
    url: https://i2.hdslb.com/bfs/face/d4d74e2d56976a8941f15f8cb5d9886311980416.jpg@150w_150h.jpg
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: false

  # Posts / Categories / Tags in sidebar.
  site_state: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimiter is the target permalink, value after `||` delimiter is the name of Font Awesome icon.
  social:
    GitHub: https://github.com/fallenwood || fab fa-github
    E-Mail: mailto:fallenwood@foxmail.com || fa fa-envelope

  social_icons:
    enable: true
    icons_only: false
    transition: false

  # Blog rolls
  links_settings:
    icon: fa fa-link
    title: Links
    # Available values: block | inline
    layout: block

  links:
    #Title: http://yoursite.com

  # Reward (Donate)
  # Front-matter variable (unsupport animation).
  reward_settings:
    # If true, reward will be displayed in every article by default.
    enable: false
    animation: false
    #comment: Donate comment here.

  reward:
    #wechatpay: /images/wechatpay.png
    #alipay: /images/alipay.png
    #paypal: /images/paypal.png
    #bitcoin: /images/bitcoin.png

  # Subscribe through Telegram Channel, Twitter, etc.
  # Usage: `Key: permalink || icon` (Font Awesome)
  follow_me:
    Twitter: https://twitter.com/yuy0216 || fab fa-twitter
    Telegram: https://t.me/fallenwood || fab fa-telegram

  # Show previous post and next post in post footer if exists
  # Available values: left | right | false
  post_navigation: right



  # ---------------------------------------------------------------
  # SEO Settings
  # ---------------------------------------------------------------

  # Disable Baidu transformation on mobile devices.
  disable_baidu_transformation: true

  # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
  baidu_push: true


  # ---------------------------------------------------------------
  # Third Party Plugins & Services Settings
  # See: https://theme-next.org/docs/third-party-services/
  # More plugins: https://github.com/theme-next/awesome-next
  # You may need to install dependencies or set CDN URLs in `vendors`
  # There are two different CDN providers by default:
  #   - jsDelivr (cdn.jsdelivr.net), works everywhere even in China
  #   - CDNJS (cdnjs.cloudflare.com), provided by cloudflare
  # ---------------------------------------------------------------

  # Math Formulas Render Support
  math:
    # Default (true) will load mathjax / katex script on demand.
    # That is it only render those page which has `mathjax: true` in Front-matter.
    # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
    per_page: true

    # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
    mathjax:
      enable: false
      # See: https://mhchem.github.io/MathJax-mhchem/
      mhchem: false

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
    katex:
      enable: false
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      copy_tex: false

  # Easily enable fast Ajax navigation on your website.
  # Dependencies: https://github.com/theme-next/theme-next-pjax
  pjax: false

  # FancyBox is a tool that offers a nice and elegant way to add zooming functionality for images.
  # For more information: https://fancyapps.com/fancybox
  fancybox: true

  # A JavaScript library for zooming images like Medium.
  # Do not enable both `fancybox` and `mediumzoom`.
  # For more information: https://github.com/francoischalifour/medium-zoom
  mediumzoom: false

  # Vanilla JavaScript plugin for lazyloading images.
  # For more information: https://github.com/ApoorvSaxena/lozad.js
  lazyload: true

  # Pangu Support
  # For more information: https://github.com/vinta/pangu.js
  pangu: false

  # ---------------------------------------------------------------
  # Comments Settings
  # See: https://theme-next.org/docs/third-party-services/comments
  # ---------------------------------------------------------------

  # Multiple Comment System Support
  comments:
    # Available values: tabs | buttons
    style: tabs
    # Choose a comment system to be displayed by default.
    # Available values: changyan | disqus | disqusjs | gitalk | livere | valine
    active: 
    # Setting `true` means remembering the comment system selected by the visitor.
    storage: true
    # Lazyload all comment systems.
    lazyload: true
    # Modify texts or order for any navs, here are some examples.
    nav:
      #disqus:
      #  text: Load Disqus
      #  order: -1
      #gitalk:
      #  order: -2

  # Valine
  # For more information: https://valine.js.org, https://github.com/xCss/Valine
  valine:
    enable: false
    appid: # Your leancloud application appid
    appkey: # Your leancloud application appkey
    notify: false # Mail notifier
    verify: false # Verification code
    placeholder: Just go go # Comment box placeholder
    avatar: mm # Gravatar style
    guest_info: nick,mail,link # Custom comment header
    pageSize: 10 # Pagination size
    language: # Language, available values: en, zh-cn
    visitor: false # Article reading statistic
    comment_count: true # If false, comment count will only be displayed in post page, not in home page
    recordIP: false # Whether to record the commenter IP
    serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
    #post_meta_order: 0

  # LiveRe comments system
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere_uid: # <your_uid>

  # Gitalk
  # For more information: https://gitalk.github.io, https://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id: # GitHub repo owner
    repo: # Repository name to store issues
    client_id: # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret
    admin_user: # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
    distraction_free_mode: true # Facebook-like distraction free mode
    # Gitalk's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
    language:


  # Local Search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: false
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false
